Location reading interval
Kuama-IT/ios-location-listener pull request #4
Opened 2021-05-26 15:32 UTC by matteoKuama

Stream location now manages also the notifications that keeps to send the locations even if the app is killed. 
It is possibile to set the notification interval and it must be >=60 seconds. 
It is possible to set the accuracy and to customise the notification message content. 
The **UserNotificationDelegate.swift** and **LocationUtility.swift** files are no longer needed.

2021-05-27 05:27 UTC, kuamanet commented
@matteoKuama 
This is an example on how you should write the comments:
```
/**
 This method sum two double numbers and returns.

 Here is the discussion. This methods adds two double and return the optional Double.


 - parameter number1: First Double Number.
 - parameter number2: Second Double Number.
 - returns: The sum of two double numbers.

 # Notes: #
 1. Parameters must be **double** type
 2. Handle return type because it is optional.

 # Example #
\`\`\`
 if let sum = self.add(number1: 23, number2: 34) {
  print(sum)
 }
 \`\`\`
*/
```

Also please create constants with reasonable names for the magic numbers  inside `LocationUtility` and evaluate the possibility to transform those static methods into extensions

2021-05-28 14:40 UTC, matteoKuama commented
Added comments for StreamLocation.swift.
UserNotificationDelegate.swift and LocationUtility.swift files are no longer needed, so they can be deleted.

2021-06-15 05:45 UTC, kuamanet requested changes

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/StreamLocation.swift
> + let streamLocation = StreamLocation()
```suggestion
\`\`\`
 let streamLocation = StreamLocation()
```

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/StreamLocation.swift
>   */
```suggestion
\`\`\`
 */
```

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/StreamLocation.swift
> +    public func setNotificationContent(title: String?, body: String?){
```suggestion
    public func setNotificationContent(title: String? = nil, body: String? = nil){
```

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/StreamLocation.swift
> +    public func setAccuracy(accuracy: Accuracy){
```suggestion
    public func setAccuracy(_ accuracy: Accuracy){
```

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/StreamLocation.swift
> +    public func setNotificationTimeInterval(timeInterval: Double){
```suggestion
    public func setNotificationTimeInterval(_ timeInterval: Double){
```

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/StreamLocation.swift
> +     streamLocation.setNotificationTimeInterval(timeInterval: 90.0)
```suggestion
     streamLocation.setNotificationTimeInterval(90.0)
```

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/StreamLocation.swift
> +     This method sets the trigger that will launch a notification.
```suggestion
```

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/StreamLocation.swift
> +    func showNotification(notificationTitle: String, notificationBody: String, timeInterval: Double, repeats: Bool) {
```suggestion
    func showNotification(withTitle notificationTitle: String, andBody notificationBody: String, andInterval timeInterval: Double, repeats: Bool) {
```

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/StreamLocation.swift
> +
```suggestion
```

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/StreamLocation.swift
> +     When this method is invoked, it starts to read the location of the user and register a notification that will start to appear when the app goes in background.
```suggestion
     When this method is invoked, it starts to read the location of the user and register a notification that will start to appear when the app goes in background.
```

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/StreamLocation.swift
> +     #Notes: #
```suggestion
     # Notes: #
```

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/StreamLocation.swift
> +     #Example: #
```suggestion
     # Example: #
```

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/StreamLocation.swift
> +     When this method is invoked, it stops to read the location of the user when the app is foreground or in the background. To stop the updates also when the app is terminated, you should call stopU
```suggestion
     When this method is invoked, it stops to read the location of the user when the app is foreground or in the background. To stop the updates also when the app is terminated, you should call stopUpdates.
```

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/StreamLocation.swift
> +     #Notes: #
```suggestion
     # Notes: #
```

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/StreamLocation.swift
> +     #Example: #
```suggestion
     # Example: #
```

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/StreamLocation.swift
> +     This method stops to register the location of the user when it is in foreground, background and terminated. It also removes all the notifications, both pending and delivered.
```suggestion
This method stops to register the location of the user when it is in foreground, background and terminated. It also removes all the notifications, both pending and delivered.
```

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/StreamLocation.swift
> +     #Notes: #
```suggestion
     # Notes: #
```

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/StreamLocation.swift
> +     #Example: #
```suggestion
     # Example: #
```

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/StreamLocation.swift
> +
```suggestion
```

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/StreamLocation.swift
> +     #Notes: #
```suggestion
     # Notes: #
```

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/StreamLocation.swift
> +
```suggestion
```

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/UserNotificationDelegate.swift
> +        completionHandler([.badge)
```suggestion
        completionHandler([.badge])
```

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/LocationUtility.swift
> +    }
These shuold be inside a `Double` [extension](https://docs.swift.org/swift-book/LanguageGuide/Extensions.html)

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/LocationUtility.swift
> +    }
This should be a `CLLocation` [extension](https://docs.swift.org/swift-book/LanguageGuide/Extensions.html) and the `distance` should be a parameter

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/StreamLocation.swift
> +//  LocationRequest.swift
Is it intentional? The file is still named `StreamLocation.swift`

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/StreamLocation.swift
> +
```suggestion
```

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/StreamLocation.swift
> +    private var notificationTimeInterval = 60.0 // default value in seconds
Create a constant instead of using a magic number

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/StreamLocation.swift
> +    private let minimumTimeInterval = 60.0 // in seconds
Create a constant instead of using a magic number

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/StreamLocation.swift
> +     This method sets the delegate for the location manager, the accuracy, the distance filter,
```suggestion
     This method sets the delegate for the location manager, the accuracy, the distance filter, 
```

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/StreamLocation.swift
> +            print("Provide authorizations")
Shouldn't we throw an error here?

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/StreamLocation.swift
> +    This method checks if the locations services are enabled and if it's possible to monitor the location.
```suggestion
This method checks if the locations services are enabled and if it's possible to monitor the location.
```

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/StreamLocation.swift
> +     This method takes a value for accuracy and set the correspondant value for the location updates.
```suggestion
This method takes a value for accuracy and set the correspondant value for the location updates.
```

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/StreamLocation.swift
> +     This method sets the time interval between each notification
```suggestion
This method sets the time interval between each notification
```

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/StreamLocation.swift
> +    This method asks for the authorizations to display notifications and it schedule the launch of a new notification.
```suggestion
This method asks for the authorizations to display notifications and it schedule the launch of a new notification.
```

2021-06-15 05:45 UTC, kuamanet commented on ios-location-listener/Classes/StreamLocation.swift
> +     This method ovverrides from the NotificationCenterDelegate protocol. This method is automatically called before the notification appears on the screen. When this method is invoked, it requests f
```suggestion
This method overrides from the NotificationCenterDelegate protocol. This method is automatically called before the notification appears on the screen. When this method is invoked, it requests for a new location update and it sends it to the stream.
```

2021-06-16 14:53 UTC, kuamanet approved these changes

2021-06-16 14:53 UTC, merged